# Site settings
title: Least Recently Used
description: > # this means to ignore newlines until "baseurl:"
  Least Recently Used
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lru.github.io" # the base hostname & protocol for your site
github_username: lru

# Build settings
markdown: kramdown
